### PR TITLE
more network modes

### PR DESCRIPTION
**Pull request by keks2293**

### CODE REVIEW

**Review by Bauuuuu — COMMENTED** [review]
Did you checked if the standalone modes works properly ?
Last time i checked LTE only did not worked that is why i decided to go with more general modes

**Comment by keks2293** [comment]
Если выбирать эти варианты через инженерное меню, то они работают, значит и так должны работать

**Comment by Bauuuuu** [comment]
OK i will test this

**Comment by Bauuuuu** [comment]
This does not work. Only three choices can be selected LTE recommended, 3G, 2G .... rest does not work

**Comment by keks2293** [comment]
Значит косяк в vendor, может в логах видно

**Pull request closed without merging**
